[build]
  command = "npm run prisma:setup && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  
[dev]
  framework = "nuxt"
  command = "npm run dev"
  port = 3000
  targetPort = 3000 